// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzsxwjrwreqhyfsjvruu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6c3h3anJ3cmVxaHlmc2p2cnV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjE3NzcsImV4cCI6MjA2ODM5Nzc3N30.T0LAEoRqLsp4vBJSHnpuc0fwh2S8RsxMi6dIM4a1FSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});